version: '3'
services:
  tm351:
    image: ouvocl/vce-tm351-jh:22j-b6
    volumes:
      - ./tm351:/home/jovyan/tm351
      - ./openrefine:/home/jovyan/openrefine
      - ./work:/home/jovyan/work
    ports:
      - '35180:8888'
    restart: unless-stopped
    environment:
      JUPYTER_TOKEN: letmein
