version: '3'
services:
  tm351:
    image: mmh352/tm351
    volumes:
      - ./workspace/tm351:/home/jovyan/tm351
      - ./workspace/openrefine:/home/jovyan/openrefine
      - ./workspace/work:/home/jovyan/work
    ports:
      - '35180:8888'
    restart: unless-stopped
    environment:
      JUPYTER_TOKEN: letmein
